##-----------------------------------------------------------------------------
## Main database configuration
##-----------------------------------------------------------------------------

nuxeo.db.name=nuxeodb
nuxeo.db.user=nuxeo
nuxeo.db.password=password
nuxeo.db.host=postgres
nuxeo.db.port=5432
## Pools
#nuxeo.db.min-pool-size=
#nuxeo.db.max-pool-size=
#nuxeo.vcs.min-pool-size=
#nuxeo.vcs.max-pool-size=
## Database transaction timeout in seconds (tomcat only)
#nuxeo.db.transactiontimeout=300

nuxeo.db.singleDataSource=false

# TODO : mode XA inactif à étudier
#nuxeo.db.xaMode=true

##-----------------------------------------------------------------------------
## Soft delete
##-----------------------------------------------------------------------------
nuxeo.soft.delete.enabled=true

##-----------------------------------------------------------------------------
## Triskells database & binaries configuration
##-----------------------------------------------------------------------------
nuxeo.db.workspaces.repository=workspaces
nuxeo.db.workspaces.host=postgres
nuxeo.db.workspaces.port=5432
nuxeo.db.workspaces.name=workspacesdb
nuxeo.db.workspaces.user=nuxeo
nuxeo.db.workspaces.password=password
nuxeo.db.workspaces.datadir=/var/lib/nuxeo/workspaces-binaries

##-----------------------------------------------------------------------------
## Espaces ecole database configuration
##-----------------------------------------------------------------------------
nuxeo.db.modulo.repository=modulo
nuxeo.db.modulo.host=postgres
nuxeo.db.modulo.port=5432
nuxeo.db.modulo.name=modulodb
nuxeo.db.modulo.user=nuxeo
nuxeo.db.modulo.password=password
nuxeo.db.modulo.datadir=/var/lib/nuxeo/modulo-binaries


##-----------------------------------------------------------------------------
## Notifications database configuration
##-----------------------------------------------------------------------------
nuxeo.db.notifications.repository=notifications
nuxeo.db.notifications.host=postgres
nuxeo.db.notifications.port=5432
nuxeo.db.notifications.name=notificationsdb
nuxeo.db.notifications.user=nuxeo
nuxeo.db.notifications.password=password
nuxeo.db.notifications.datadir=/var/lib/nuxeo/notifications-binaries
