JAVA_OPTS=$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787

org.nuxeo.dev=true
nuxeo.cors.urls=*
nuxeo.templates=default,postgresql,workspaces

nuxeo.defaultAdministratorId=8e8454f4-5771-47b4-9da9-02f2ee6400dc

