version: '3.8'

services:
  postgres-nuxeo-2023:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-nuxeo-2023-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512m
    profiles:
      - nuxeo-2023

  elasticsearch-nuxeo-2023:
    image: elasticsearch:8.7.0
    environment:
      - cluster.name=es-nuxeo-2023-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200"
    volumes:
      - elasticsearch-nuxeo-2023-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 50
    profiles:
      - nuxeo-2023

  nuxeo-2023:
    build:
      context: ./nuxeo-2023
      args:
        BUILD_TAG: local-nuxeo-nuxeo
        SCM_REF: built-locally
        VERSION: latest-lts-2023
    ports:
      - "8080"
      - "8787"
    depends_on:
      postgres-nuxeo-2023:
        condition: service_started
      elasticsearch-nuxeo-2023:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2g
    profiles:
      - nuxeo-2023

  kibana-nuxeo-2023:
    image: kibana:8.7.0
    ports:
      - "5601"
    depends_on:
      - elasticsearch-nuxeo-2023
    deploy:
      resources:
        limits:
          memory: 512m
    profiles:
      - nuxeo-2023

volumes:
  postgres-nuxeo-2023-data:
  elasticsearch-nuxeo-2023-data:
