services:

  opendj:
    build: opendj
    image: registry.roqu.io:5043/triskell-opendj
    restart: unless-stopped
    expose:
      - "1389"
    volumes:
      - opendj-data:/opt/opendj/db

  cas:
    build: cas
    image: registry.roqu.io:5043/triskell-cas
    restart: unless-stopped
    environment:
      - LDAP_HOST=opendj
    expose:
      - "8080"
    links:
      - opendj
    deploy:
      resources:
        limits:
          memory: 1gb

  httpd:
    build:
      context: httpd
      args:
        - TRISKELL_PUBLIC_HOST=demo.roqu.io
    image: registry.roqu.io:5043/triskell-httpd
    restart: unless-stopped
    depends_on:
      - cas
      - nuxeo
      - back-end
      - front-end
    ports:
      - "8180:80"

  postgres:
    build: postgres
    image: registry.roqu.io:5043/triskell-postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=nuxeo
      - POSTGRES_MULTIPLE_DATABASES=nuxeodb, modulodb, workspacesdb, notificationsdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          memory: 1gb

  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1gb
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 50

  kafka:
    image: apache/kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafka:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    deploy:
      resources:
        limits:
          memory: 1gb

  nuxeo:
    build:
      context: ./nuxeo
      args:
        BUILD_TAG: local-nuxeo-nuxeo
        SCM_REF: built-locally
        VERSION: latest-lts-2023
    image: registry.roqu.io:5043/triskell-nuxeo
    expose:
      - "8080"
    volumes:
      - nuxeo-data:/var/lib/nuxeo
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1gb

  back-end:
    build: back-end
    image: registry.roqu.io:5043/triskell-back-end
    expose:
      - "8080"

  front-end:
    build: front-end
    image: registry.roqu.io:5043/triskell-front-end
    expose:
      - "80"


volumes:
  opendj-data:
  postgres-data:
  elasticsearch-data:
  nuxeo-data:
