version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512m

  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 50

  nuxeo:
    build:
      context: ./nuxeo
      args:
        BUILD_TAG: local-nuxeo-nuxeo
        SCM_REF: built-locally
        VERSION: latest-lts-2023
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2g

  kibana:
    image: kibana:8.7.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  postgres-data:
  elasticsearch-data:
